name: player

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup SSH keys
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts

    - name: Deploy to Server
      run: |
        ssh -o StrictHostKeyChecking=no -T ${{ secrets.USERNAME }}@${{ secrets.HOST }} 'cd /home/steckbrief/data && git pull git@github.com:TigerKopf/efb.git'

    - name: Check if deployment was successful

      run: echo "Deployment successful! 🚀"
